version: "3"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
    ports:
      - "5433:5432"

  migration:
    build:
      dockerfile: Dockerfile.migration
    depends_on:
      - db
    command: npx sequelize-cli db:migrate
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth
      DB_PORT: 5432
      NODE_ENV: docker
    
  server:
    build:
      context: .
      args:
        - no_cache=1
    depends_on:
      - db
      - redis
    ports:
      - "5000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth
      DB_PORT: 5432
      NODE_ENV: docker